# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiples', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integer',
            name='integer',
            field=models.IntegerField(),
        ),
    ]
