# Generated by Django 4.0.4 on 2022-05-30 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('multiples', '0002_alter_integer_integer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Integer',
        ),
    ]
